### ISSUE TITLE
Encoding 1251 data could not be found

### ISSUE THREAD

**Issue by XFox111** [XFox111/GUTSchedule#15]
### Description
On some devices (Google Play testers) application throws `System.NotSupportedException` 

### Reproduction steps
Unknown, possibly changing device regional settings to (?)
According to video reports, It happens only on the export process

### Expected behavior
No exception should be thrown. The app should export schedule

### Screenshots
Video demos are attached to Google Play testing reports and will be sent by assignees' demand

### Environment
Please complete the following information:
 - Device: Samsung Galaxy S3, S9, Huawei Mate 9, Nokia 1, LGE K3  2017
 - Android OS version: 8.0, 4.3, 7.0, 8.1 (Go edition), 6.0
 - Application version: 257 (CI build numer #20200206.1)

### Additional context
Stack trace:
```
FATAL EXCEPTION: main
Process: com.xfox111.gut.schedule, PID: 28306
android.runtime.JavaProxyThrowable: System.NotSupportedException: Encoding 1251 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
  at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x0022d] in <a6d893eee8704b7785d1d1b5410d0f5b>:0 
  at System.Text.Encoding.GetEncoding (System.String name) [0x00012] in <a6d893eee8704b7785d1d1b5410d0f5b>:0 
  at GUT.Schedule.Extensions.GetString (System.Net.Http.HttpResponseMessage response) [0x00027] in <2215810725ad4aaeb95d73ce3822a14c>:0 
  at GUT.Schedule.Activities.MainActivity.Export_Click (System.Object sender, System.EventArgs e) [0x002bc] in <2215810725ad4aaeb95d73ce3822a14c>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <a6d893eee8704b7785d1d1b5410d0f5b>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <03400fe528f64570b9442c743326f3eb>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <03400fe528f64570b9442c743326f3eb>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <03400fe528f64570b9442c743326f3eb>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.7(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by XFox111** [comment]
Waiting for testers confirmation
